#!/usr/bin/env python3
"""
Build the Layer A ontology resource tree for the humanitarian-data-analyst skill.

Reads the per-node draft YAML files (from the step-09 build) and emits:
  ontology/
    index.yaml                 # compact routing surface (all nodes, ~1 line each)
    sectors/ _axis.yaml + <node>.yaml
    pillars_1d/  ...
    subpillars_1d/ ...
    pillars_2d/ ...
    subpillars_2d/ ...

Usage:
  python3 scripts/build_layer_a.py <path-to>/ontology_drafts ontology
"""
import re
import sys
from pathlib import Path

import yaml

SRC_DRAFTS = Path(sys.argv[1])
OUT_ROOT = Path(sys.argv[2])

AXIS = {
    "sector":       ("sectors",       "Sectors"),
    "pillar_1d":    ("pillars_1d",    "Pillars 1D"),
    "subpillar_1d": ("subpillars_1d", "Subpillars 1D"),
    "pillar_2d":    ("pillars_2d",    "Pillars 2D"),
    "subpillar_2d": ("subpillars_2d", "Subpillars 2D"),
}

AXIS_DESC = {
    "sectors": (
        "The 11 humanitarian sectors (WASH, Protection, Health, Education, Food Security, "
        "Shelter, Livelihoods, Nutrition, Logistics, Agriculture, Cross). Answers 'what domain of need?'"
    ),
    "pillars_1d": (
        "Pillars 1D describe the TYPE OF INFORMATION (Context, Shock/Event, Displacement, "
        "Casualties, Humanitarian Access, Information And Communication). Orthogonal to the 2D axis."
    ),
    "subpillars_1d": "Children of the 1D pillars — finer-grained 'type of information' categories.",
    "pillars_2d": (
        "Pillars 2D describe the ANALYTICAL LENS (Humanitarian Conditions, At Risk, "
        "Capacities & Response, Impact, Priority Interventions/Needs). Orthogonal to 1D: an excerpt "
        "can carry both a 1D and a 2D tag."
    ),
    "subpillars_2d": (
        "Children of the 2D pillars. Most sibling confusion lives here; consult "
        "distinguish_from before committing."
    ),
}


def slugify(label: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", label.lower()).strip("_")


def first_sentence(text: str, limit: int = 200) -> str:
    text = " ".join(text.split())
    m = re.search(r"\.\s", text)
    s = text[: m.start() + 1] if m else text
    if len(s) > limit:
        s = s[: limit - 1].rstrip() + "…"
    return s


def main():
    OUT_ROOT.mkdir(parents=True, exist_ok=True)
    index = {"axes": {}, "nodes": []}

    for folder, desc in AXIS_DESC.items():
        (OUT_ROOT / folder).mkdir(exist_ok=True)
        (OUT_ROOT / folder / "_axis.yaml").write_text(yaml.safe_dump(
            {"axis": folder, "description": desc, "lookup": "one file per node in this folder"},
            sort_keys=False, allow_unicode=True))
        index["axes"][folder] = desc

    count = 0
    for draft in sorted(SRC_DRAFTS.glob("*.yaml")):
        data = yaml.safe_load(draft.read_text())
        if not data:
            continue
        (node_key, body), = data.items()
        prefix, _, label_path = node_key.partition("::")
        if prefix not in AXIS:
            print(f"  ! unknown prefix {prefix!r} in {draft.name}", file=sys.stderr)
            continue
        folder, _ = AXIS[prefix]
        segments = label_path.split("->")
        label = segments[-1]
        parent = "->".join(segments[:-1]) if len(segments) > 1 else None
        node_id = slugify(label_path.replace("->", "_"))
        filename = f"{node_id}.yaml"
        (OUT_ROOT / folder / filename).write_text(
            yaml.safe_dump({node_key: body}, sort_keys=False, allow_unicode=True, width=100))
        desc = body.get("description", "") or ""
        index["nodes"].append({
            "id": node_id, "key": node_key, "axis": folder, "label": label, "parent": parent,
            "gist": first_sentence(desc), "synonyms": body.get("synonyms", []) or [],
            "file": f"ontology/{folder}/{filename}",
        })
        count += 1

    axis_order = list(AXIS_DESC.keys())
    index["nodes"].sort(key=lambda n: (axis_order.index(n["axis"]), n["label"]))
    index["node_count"] = count
    header = (
        "# Layer A routing index - humanitarian-data-analyst skill\n"
        "# Compact surface for routing analyst questions to ontology nodes.\n"
        "# Match the question against gist + synonyms, then open the file for the full\n"
        "# description, example_questions, and distinguish_from before committing.\n"
        f"# {count} nodes across 5 axes. Generated by build_layer_a.py - do not hand-edit.\n\n"
    )
    (OUT_ROOT / "index.yaml").write_text(
        header + yaml.safe_dump(index, sort_keys=False, allow_unicode=True, width=100))
    print(f"Wrote {count} node files + index.yaml to {OUT_ROOT}")


if __name__ == "__main__":
    main()
